// SPDX-License-Identifier: MIT
// Author:  Giovanni Santini
// Mail:    giovanni.santini@proton.me
// Github:  @San7o

#include "errors.h"

const char* haplo_error_string(int error)
{
  switch(error)
  {
  case HAPLO_ERROR_LEXER_END_OF_INPUT:
    return "ERROR_LEXER_END_OF_INPUT";
  case HAPLO_ERROR_PARSER_TOKEN_UNRECOGNIZED:
    return "ERROR_PARSER_TOKEN_UNRECOGNIZED";
  case HAPLO_ERROR_MALFORMED_PARENTHESIS:
    return "ERROR_MALFORMED_PARENTHESIS";
  case HAPLO_ERROR_PARSER_MISSING_OPEN:
    return "ERROR_PARSER_MISSING_OPEN";
  case HAPLO_ERROR_PARSER_MISSING_CLOSE:
    return "ERROR_PARSER_MISSING_CLOSE";
  case HAPLO_ERROR_INTERPRETER_UNKNOWN_SYMBOL:
    return "ERROR_INTERPRETER_UNKNOWN_SYMBOL";
  case HAPLO_ERROR_INTERPRETER_UNKNOWN_SYMBOL_TYPE:
    return "ERROR_INTERPRETER_UNKNOWN_SYMBOL_TYPE";
  case HAPLO_ERROR_STACK_NULL:
    return "ERROR_STACK_NULL";
  case HAPLO_ERROR_INTERPRETER_NULL:
    return "ERROR_INTERPRETER_NULL";
  case HAPLO_ERROR_EXPR_NULL:
    return "ERROR_EXPR_NULL";
  case HAPLO_ERROR_PARSER_NULL:
    return "ERROR_PARSER_NULL";
  case HAPLO_ERROR_PARSER_INPUT_NULL:
    return "ERROR_PARSER_INPUT_NULL";
  case HAPLO_ERROR_LEXER_INPUT_NULL:
    return "ERROR_LEXER_INPUT_NULL";
  case HAPLO_ERROR_STACK_EMPTY:
    return "ERROR_STACK_EMPTY";
  case HAPLO_ERROR_PARSER_NEXT_TOKEN:
    return "ERROR_PARSER_NEXT_TOKEN";
  case HAPLO_ERROR_PARSER_STRING_LITERAL_END:
    return "ERROR_PARSER_STRING_LITERAL_END";
  case HAPLO_ERROR_LEXER_ATOM_STRING_SIZE:
    return "ERROR_LEXER_ATOM_STRING_SIZE";
  case HAPLO_ERROR_INTERPRETER_INVALID_TYPE:
    return "ERROR_INTERPRETER_INVALID_TYPE";
  case HAPLO_ERROR_INTERPRETER_NOT_FUNCTION:
    return "ERROR_INTERPRETER_NOT_FUNCTION";
  case HAPLO_ERROR_INTERPRETER_WRONG_NUMBER_OF_ARGS:
    return "ERROR_INTERPRETER_WRONG_NUMBER_OF_ARGS";
  case HAPLO_ERROR_SYMBOL_MAP_NULL:
    return "ERROR_SYMBOL_MAP_NULL";
  case HAPLO_ERROR_SYMBOL_MAP_NOT_INITIALIZED:
    return "ERROR_SYMBOL_MAP_NOT_INITIALIZED";
  case HAPLO_ERROR_SYMBOL_MAP_LOOKUP_NOT_FOUND:
    return "ERROR_SYMBOL_MAP_LOOKUP_NOT_FOUND";
  case HAPLO_ERROR_VALUE_TYPE_UNRECOGNIZED:
    return "ERROR_VALUE_TYPE_UNRECOGNIZED";
  case HAPLO_ERROR_PARSER_UNEXPECTED_TOKEN:
    return "ERROR_PARSER_UNEXPECTED_TOKEN";
  case HAPLO_ERROR_LEXER_NULL:
    return "ERROR_LEXER_NULL";
  }
  return "ERROR_UNKNOWN";
}
